### ISSUE TITLE
Will not compile on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [korfuri/OPL33t#1]
$ make
g++ -Isrc/deps/libbinio/src -Wsuggest-override -std=c++11  -DSLUG=OPL33t -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/OPL33t.cpp.o src/OPL33t.cpp
g++ -Isrc/deps/libbinio/src -Wsuggest-override -std=c++11  -DSLUG=OPL33t -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Player.cpp.o src/Player.cpp
src/Player.cpp:7:10: fatal error: deps/adlmidi/src/dbopl.h: No such file or directory
 #include "deps/adlmidi/src/dbopl.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:65: build/src/Player.cpp.o] Error 1

**Comment by korfuri** [comment]
Did you pull the git submodules? This include should be present on all platforms.

**Comment by SteveRussell33** [comment]
This is the error I get:

g++ -Isrc/deps/libbinio/src -Wsuggest-override -std=c++11  -DSLUG=OPL33t -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Player.cpp.o src/Player.cpp
In file included from src/deps/adplug/src/player.h:27,
                 from src/deps/adplug/src/adplug.h:27,
                 from src/Player.cpp:13:
src/deps/adplug/src/fprovide.h:26:10: fatal error: binio.h: No such file or directory
   26 | #include <binio.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:65: build/src/Player.cpp.o] Error 1

Header file is missing from adplug submodule.

**Comment by korfuri** [comment]
I believe this is due to libbinio's build instructions having a special Windows case to generate the binio.h file. You can just `cp binio.h.in binio.h` and it should work, according to https://github.com/adplug/libbinio/blob/master/INSTALL#L40

This being said, I have not been successful releasing this for Windows. Since I don't have a Windows to test on, it's probably going  to stay that way unless someone wants to contribute Windows support.
